receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"

connectors:
  routing:
    default_pipelines: [traces]
    table:
      - context: request
        condition: request["X-Tenant"] == "debug"
        pipelines: [traces/other]

exporters:
  otlp/elastic:
    endpoint: ${ELASTIC_ENDPOINT}
    headers:
      Authorization: "ApiKey ${ELASTIC_API_KEY}"
  otlp/elastic-cloud:
    endpoint: ${SYNTHETICS_DEPLOYMENT}
    headers:
      Authorization: "ApiKey ${SYNTHETICS_API_KEY}"

  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/elastic, otlp/elastic-cloud] 
    traces/other:
      receivers: [otlp]
      exporters: [debug] 
    logs:
      receivers: [otlp]
      exporters: [otlp/elastic, otlp/elastic-cloud] 
    metrics:
      receivers: [otlp]
      exporters: [otlp/elastic, otlp/elastic-cloud] 
